### ISSUE TITLE
replace table impl. with an alternative one?

### ISSUE THREAD

**Issue by devoncarew** [mosuem/dart_pr_dashboard#2]
I have a flutter table implementation that I've used in a few projects. Any concerns w/ replacing the table implementation here w/ a different one? It has a few more built-ins for sorting, table column sizing and alignment, row + cell validation, ...

**Comment by mosuem** [comment]
I originally used that table, but there was an issue with row heights - so I switched to my own.

**Comment by devoncarew** [comment]
Gotcha; I may send a few PRs then (nothing specific, just some more visual tweaks to the layout).
